# .github/workflows/azure-static-web-apps.yml
name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            api/package-lock.json

      - name: Harden npm network (retries)
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 120000
          npm config set prefer-online false

      - name: Install root deps
        run: npm ci --no-audit --no-fund

      - name: Install API deps (Functions)
        working-directory: api
        run: npm ci --omit=dev --no-audit --no-fund

      - name: Build (retry x3 on transient failures)
        run: |
          for i in 1 2 3; do
            npm run build && break
            echo "Build failed (attempt $i). Retrying..."
            sleep $((i*10))
          done

      # ... your existing SWA deploy step (leave as-is) ...
      # Example:
      # - name: Deploy to Azure Static Web Apps
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: "upload"
      #     app_location: "/"
      #     api_location: "api"
      #     output_location: "dist"
